sudo: false
language: node_js
node_js:
  - node
  - lts/*
cache: npm
notifications:
  email: false
node_js: 'lts/*'
install: npm install && lerna bootstrap
script: npm run verify
branches:
  only: master
