sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: cd packages/karhu && npm install; cd ../react-karhu && npm install; cd ../../
script: npm run verify
branches:
  only: master
